/*By Jiasong Sun*/function slideShow(l,d,g,e){var b=0,f=null,c={timer1:null,timer2:null,timer3:null,timer4:null},a=document.getElementById("slideShowPic").children,s=document.getElementById("slideIndex");s.innerHTML="";for(var h=0;h<a.length;h++)s.appendChild(document.createElement("li"));var k=s.children;a[0].style.zIndex=10;k[0].className="selected";for(var f=setInterval(function(){if(b===a.length-1){var f=a[b],d=a[0];k[b].className="";k[0].className="selected";b=0}else f=a[b],d=a[b+1],k[b].className="",k[b+1].className=
"selected",b++;l(a,f,d,g,e,c)},d),h=function(h){return function(){if(h!==b){var r=a[b],m=a[h];k[b].className="";k[h].className="selected";h>b?l(a,r,m,g,e,c):l(a,r,m,-g,-e,c);b=h;clearInterval(f);f=setInterval(function(){if(b===a.length-1){var f=a[b],d=a[0];k[b].className="";k[0].className="selected";b=0}else f=a[b],d=a[b+1],k[b].className="",k[b+1].className="selected",b++;l(a,f,d,g,e,c)},d)}}},p=0;p<k.length;p++)k[p].onclick=h(p);var q=document.getElementById("next");q.style.top=Math.abs(e)/2-22.5+
"px";q.onclick=function(){if(b===a.length-1){var h=a[b],r=a[0];k[b].className="";k[0].className="selected";b=0}else h=a[b],r=a[b+1],k[b].className="",k[b+1].className="selected",b++;l(a,h,r,g,e,c);clearInterval(f);f=setInterval(function(){if(b===a.length-1){var f=a[b],d=a[0];k[b].className="";k[0].className="selected";b=0}else f=a[b],d=a[b+1],k[b].className="",k[b+1].className="selected",b++;l(a,f,d,g,e,c)},d)};var m=document.getElementById("prev");m.style.top=Math.abs(e)/2-22.5+"px";m.onclick=function(){if(0===
b){var h=a[0],r=a[a.length-1];k[0].className="";k[a.length-1].className="selected";b=a.length-1}else h=a[b],r=a[b-1],k[b].className="",k[b-1].className="selected",b--;l(a,h,r,-g,-e,c);clearInterval(f);f=setInterval(function(){if(b===a.length-1){var f=a[b],d=a[0];k[b].className="";k[0].className="selected";b=0}else f=a[b],d=a[b+1],k[b].className="",k[b+1].className="selected",b++;l(a,f,d,g,e,c)},d)};h=document.getElementById("slideShow");h.onmouseover=function(){m.style.left="0px";q.style.left=Math.abs(g)-
50+"px";s.style.bottom="0px"};h.onmouseout=function(){m.style.left="-50px";q.style.left=Math.abs(g)+"px";s.style.bottom="-30px"}}
function slideShow_flipUpDown(l,d,g,e){var b=0,f=null,c={timer1:null,timer2:null,timer3:null,timer4:null},a=document.getElementById("slideShowPic").children,s=document.getElementById("slideIndex");s.innerHTML="";for(var h=0;h<a.length;h++)s.appendChild(document.createElement("li"));var k=s.children;a[0].style.zIndex=10;k[0].className="selected";for(var f=setInterval(function(){if(b===a.length-1){var f=a[b],d=a[0];k[b].className="";k[0].className="selected";b=0}else f=a[b],d=a[b+1],k[b].className=
"",k[b+1].className="selected",b++;l(a,f,d,g,e,c)},d),h=function(h){return function(){if(h!==b){var r=a[b],m=a[h];k[b].className="";k[h].className="selected";h>b?l(a,r,m,g,e,c):"flipUp"===l.toString().match(/function ([^\(]+)/)[1]?flipDown(a,r,m,g,e,c):flipUp(a,r,m,g,e,c);b=h;clearInterval(f);f=setInterval(function(){if(b===a.length-1){var f=a[b],d=a[0];k[b].className="";k[0].className="selected";b=0}else f=a[b],d=a[b+1],k[b].className="",k[b+1].className="selected",b++;l(a,f,d,g,e,c)},d)}}},p=0;p<
k.length;p++)k[p].onclick=h(p);var q=document.getElementById("next");q.style.top=Math.abs(e)/2-22.5+"px";q.onclick=function(){if(b===a.length-1){var h=a[b],r=a[0];k[b].className="";k[0].className="selected";b=0}else h=a[b],r=a[b+1],k[b].className="",k[b+1].className="selected",b++;l(a,h,r,g,e,c);clearInterval(f);f=setInterval(function(){if(b===a.length-1){var f=a[b],d=a[0];k[b].className="";k[0].className="selected";b=0}else f=a[b],d=a[b+1],k[b].className="",k[b+1].className="selected",b++;l(a,f,
d,g,e,c)},d)};var m=document.getElementById("prev");m.style.top=Math.abs(e)/2-22.5+"px";m.onclick=function(){if(0===b){var h=a[0],r=a[a.length-1];k[0].className="";k[a.length-1].className="selected";b=a.length-1}else h=a[b],r=a[b-1],k[b].className="",k[b-1].className="selected",b--;"flipUp"===l.toString().match(/function ([^\(]+)/)[1]?flipDown(a,h,r,g,e,c):flipUp(a,h,r,g,e,c);clearInterval(f);f=setInterval(function(){if(b===a.length-1){var f=a[b],d=a[0];k[b].className="";k[0].className="selected";
b=0}else f=a[b],d=a[b+1],k[b].className="",k[b+1].className="selected",b++;l(a,f,d,g,e,c)},d)};h=document.getElementById("slideShow");h.onmouseover=function(){m.style.left="0px";q.style.left=Math.abs(g)-50+"px";s.style.bottom="0px"};h.onmouseout=function(){m.style.left="-50px";q.style.left=Math.abs(g)+"px";s.style.bottom="-30px"}}
function slideShow_slicedPic(l,d,g,e,b){for(var f=document.getElementById("slideShowPic"),c=f.children,a=[],s=0;s<c.length;s++)a.push(c[s]);var h=0,k=null,p={timer1:null,timer2:null,timer3:null,timer4:null},q={done:"yes"},m=document.getElementById("slideIndex");m.innerHTML="";for(c=0;c<a.length;c++)m.appendChild(document.createElement("li"));var n=m.children;a[0].style.zIndex="10";n[0].className="selected";k=setInterval(function(){if(h===a.length-1){var c=a[h],g=a[0];n[h].className="";n[0].className=
"selected";h=0}else c=a[h],g=a[h+1],n[h].className="",n[h+1].className="selected",h++;l(f,a,c,g,e,b,p,q,d)},g);c=function(c){return function(){if("yes"===q.done&&c!==h){var r=a[h],m=a[c];n[h].className="";n[c].className="selected";l(f,a,r,m,e,b,p,q,d);h=c;clearInterval(k);k=setInterval(function(){if(h===a.length-1){var c=a[h],g=a[0];n[h].className="";n[0].className="selected";h=0}else c=a[h],g=a[h+1],n[h].className="",n[h+1].className="selected",h++;l(f,a,c,g,e,b,p,q,d)},g)}}};for(s=0;s<n.length;s++)n[s].onclick=
c(s);var r=document.getElementById("next");r.style.top=Math.abs(b)/2-22.5+"px";r.onclick=function(){if("yes"===q.done){if(h===a.length-1){var c=a[h],r=a[0];n[h].className="";n[0].className="selected";h=0}else c=a[h],r=a[h+1],n[h].className="",n[h+1].className="selected",h++;l(f,a,c,r,e,b,p,q,d);clearInterval(k);k=setInterval(function(){if(h===a.length-1){var c=a[h],g=a[0];n[h].className="";n[0].className="selected";h=0}else c=a[h],g=a[h+1],n[h].className="",n[h+1].className="selected",h++;l(f,a,c,
g,e,b,p,q,d)},g)}};var w=document.getElementById("prev");w.style.top=Math.abs(b)/2-22.5+"px";w.onclick=function(){if("yes"===q.done){if(0===h){var c=a[0],r=a[a.length-1];n[0].className="";n[a.length-1].className="selected";h=a.length-1}else c=a[h],r=a[h-1],n[h].className="",n[h-1].className="selected",h--;l(f,a,c,r,e,b,p,q,d);clearInterval(k);k=setInterval(function(){if(h===a.length-1){var c=a[h],g=a[0];n[h].className="";n[0].className="selected";h=0}else c=a[h],g=a[h+1],n[h].className="",n[h+1].className=
"selected",h++;l(f,a,c,g,e,b,p,q,d)},g)}};c=document.getElementById("slideShow");c.onmouseover=function(){w.style.left="0px";r.style.left=Math.abs(e)-50+"px";m.style.bottom="0px"};c.onmouseout=function(){w.style.left="-50px";r.style.left=Math.abs(e)+"px";m.style.bottom="-30px"}}
function fadeOut(l,d,g,e,b,f){clearInterval(f.timer1);for(e=0;e<l.length;e++)l[e].style.zIndex=1;var c=40;d.style.zIndex=10;g.style.zIndex=11;g.style.opacity=c/100;g.style.filter="alpha(opacity="+c+")";f.timer1=setInterval(function(){100===c?clearInterval(f.timer1):(c=76<=c?c+3:c+2,g.style.opacity=c/100,g.style.filter="alpha(opacity="+c+")")},40)}
function moveLeftRight(l,d,g,e,b,f){clearInterval(f.timer1);clearInterval(f.timer2);clearInterval(f.timer3);clearInterval(f.timer4);for(b=b=0;b<l.length;b++)l[b].style.zIndex=1;var c=Math.floor(0.3*-e);d.style.zIndex=10;g.style.zIndex=10;d.style.left=c+"px";g.style.left=c+e+"px";var a=-e;f.timer1=setInterval(function(){Math.abs(c-a)<Math.abs(0.1*e)?(clearInterval(f.timer1),f.timer2=setInterval(function(){Math.abs(c-a)<Math.abs(0.01*e)?(clearInterval(f.timer2),f.timer3=setInterval(function(){5>Math.abs(c-
a)?(clearInterval(f.timer3),f.timer4=setInterval(function(){c===a?clearInterval(f.timer4):(c-=0<c-a?Math.ceil((c-a)/10):Math.floor((c-a)/10),d.style.left=c+"px",g.style.left=c+e+"px")},90)):(c-=0<c-a?Math.ceil((c-a)/18):Math.floor((c-a)/18),d.style.left=c+"px",g.style.left=c+e+"px")},45)):(c-=0<c-a?Math.ceil((c-a)/13):Math.floor((c-a)/13),d.style.left=c+"px",g.style.left=c+e+"px")},35)):(c-=0<c-a?Math.ceil((c-a)/11):Math.floor((c-a)/11),d.style.left=c+"px",g.style.left=c+e+"px")},30)}
function moveUpDown(l,d,g,e,b,f){clearInterval(f.timer1);clearInterval(f.timer2);clearInterval(f.timer3);clearInterval(f.timer4);for(e=e=0;e<l.length;e++)l[e].style.zIndex=1;var c=Math.floor(0.3*-b);d.style.zIndex=10;g.style.zIndex=10;d.style.top=c+"px";g.style.top=c+b+"px";var a=-b;f.timer1=setInterval(function(){Math.abs(c-a)<Math.abs(0.1*b)?(clearInterval(f.timer1),f.timer2=setInterval(function(){Math.abs(c-a)<Math.abs(0.01*b)?(clearInterval(f.timer2),f.timer3=setInterval(function(){3>Math.abs(c-
a)?(clearInterval(f.timer3),f.timer4=setInterval(function(){c===a?clearInterval(f.timer4):(c-=0<c-a?Math.ceil((c-a)/10):Math.floor((c-a)/10),d.style.top=c+"px",g.style.top=c+b+"px")},90)):(c-=0<c-a?Math.ceil((c-a)/20):Math.floor((c-a)/20),d.style.top=c+"px",g.style.top=c+b+"px")},45)):(c-=0<c-a?Math.ceil((c-a)/12):Math.floor((c-a)/12),d.style.top=c+"px",g.style.top=c+b+"px")},35)):(c-=0<c-a?Math.ceil((c-a)/10):Math.floor((c-a)/10),d.style.top=c+"px",g.style.top=c+b+"px")},30)}
function flipUp(l,d,g,e,b,f){clearInterval(f.timer1);clearInterval(f.timer2);clearInterval(f.timer3);clearInterval(f.timer4);for(var c=0,c=0;c<l.length;c++)l[c].style.zIndex=1;var a=b;d.style.zIndex=10;g.style.zIndex=10;d.style.height=a+"px";g.style.height=b-a+"px";d.style.width=g.style.width=e+"px";d.style.top="0px";g.style.top=a+"px";f.timer1=setInterval(function(){Math.abs(a-0)<Math.abs(0.1*b)?(clearInterval(f.timer1),f.timer2=setInterval(function(){Math.abs(a-0)<Math.abs(0.01*b)?(clearInterval(f.timer2),
f.timer3=setInterval(function(){3>Math.abs(a-0)?(clearInterval(f.timer3),f.timer4=setInterval(function(){0===a?clearInterval(f.timer4):(a-=0<a-0?Math.ceil((a-0)/10):Math.floor((a-0)/10),d.style.height=a+"px",g.style.height=b+"px",d.style.width=g.style.width=e+"px",d.style.top="0px",g.style.top=a+"px")},40)):(a-=0<a-0?Math.ceil((a-0)/15):Math.floor((a-0)/15),d.style.height=a+"px",g.style.height=b-a+"px",d.style.width=g.style.width=e+"px",d.style.top="0px",g.style.top=a+"px")},35)):(a-=0<a-0?Math.ceil((a-
0)/12):Math.floor((a-0)/12),d.style.height=a+"px",g.style.height=b-a+"px",d.style.width=g.style.width=e+"px",d.style.top="0px",g.style.top=a+"px")},30)):(a-=0<a-0?Math.ceil((a-0)/12):Math.floor((a-0)/12),d.style.height=a+"px",g.style.height=b-a+"px",d.style.width=g.style.width=e+"px",d.style.top="0px",g.style.top=a+"px")},35)}
function flipDown(l,d,g,e,b,f){clearInterval(f.timer1);clearInterval(f.timer2);clearInterval(f.timer3);clearInterval(f.timer4);for(var c=0,c=0;c<l.length;c++)l[c].style.zIndex=1;var a=b;d.style.zIndex=10;g.style.zIndex=10;d.style.height=a+"px";g.style.height=b-a+"px";d.style.width=g.style.width=e+"px";d.style.top=b-a+"px";g.style.top="0px";f.timer1=setInterval(function(){Math.abs(a-0)<Math.abs(0.1*b)?(clearInterval(f.timer1),f.timer2=setInterval(function(){Math.abs(a-0)<Math.abs(0.01*b)?(clearInterval(f.timer2),
f.timer3=setInterval(function(){3>Math.abs(a-0)?(clearInterval(f.timer3),f.timer4=setInterval(function(){0===a?clearInterval(f.timer4):(a-=0<a-0?Math.ceil((a-0)/10):Math.floor((a-0)/10),d.style.height=a+"px",g.style.height=b+"px",d.style.width=g.style.width=e+"px",d.style.top=b-a+"px",g.style.top="0px")},40)):(a-=0<a-0?Math.ceil((a-0)/15):Math.floor((a-0)/15),d.style.height=a+"px",g.style.height=b-a+"px",d.style.width=g.style.width=e+"px",d.style.top=b-a+"px",g.style.top="0px")},35)):(a-=0<a-0?Math.ceil((a-
0)/12):Math.floor((a-0)/12),d.style.height=a+"px",g.style.height=b-a+"px",d.style.width=g.style.width=e+"px",d.style.top=b-a+"px",g.style.top="0px")},30)):(a-=0<a-0?Math.ceil((a-0)/12):Math.floor((a-0)/12),d.style.height=a+"px",g.style.height=b-a+"px",d.style.width=g.style.width=e+"px",d.style.top=b-a+"px",g.style.top="0px")},35)}
function slicePicShow(l,d,g,e,b,f,c,a,s){function h(a,b){for(var c=0;c<a.length;c++)if(a[c]===b)return!0;return!1}function k(a){for(var b=[];b.length<a.length;){for(q=Math.floor(Math.random()*(a.length-1+1));h(b,a[q]);)q=Math.floor(Math.random()*(a.length-1+1));b.push(a[q])}return b}clearInterval(c.timer1);a.done="no";for(var p=0;p<d.length;p++)d[p].style.zIndex="1";g.style.zIndex="12";e.style.zIndex="10";d=l.getElementsByClassName("slicedPic");for(p=0;p<d.length;p++)d[p].src=null,l.removeChild(d[p]);
var q=p=0,m=new Image,n={};m.onload=function(){for(var a=[],d=[],h=0;h<f/60;h++)for(var e=0;e<b/60;e++){var q=document.createElement("canvas");q.width=60;q.height=60;q.getContext("2d").drawImage(m,60*e,60*h,60,60,0,0,q.width,q.height);a.push(q.toDataURL())}for(p=0;p<a.length;p++)h=document.createElement("img"),h.src=a[p],h.style.zIndex="11",h.className="slicedPic",h.style.top=60*Math.floor(p/(b/60))+"px",h.style.left=60*(p%(b/60))+"px",l.appendChild(h),d.push(h),n[a[p]]=p;a=k(a);setTimeout(function(){g.style.zIndex=
"1"},10);c.timer1=setInterval(function(){0===a.length?clearInterval(c.timer1):s(d[n[a.shift()]],60,60)},1)};m.src=g.src;setTimeout(function(){a.done="yes"},1500)}
function slicePicShow_diagonal(l,d,g,e,b,f,c,a,s){function h(a){for(var c=[],d=0,g=0;g<f/n+b/m-1;g++){var h=[];var e=g<b/m?b/m-1-g:d+=b/m;for(h.push(a[e]);e+b/m+1<a.length&&1===Math.floor((e+b/m+1)/(b/m))-Math.floor(e/(b/m));)e=e+b/m+1,h.push(a[e]);c.push(h)}return c}clearInterval(c.timer1);a.done="no";for(var k=0;k<d.length;k++)d[k].style.zIndex="1";g.style.zIndex="12";e.style.zIndex="10";d=l.getElementsByClassName("slicedPic");for(k=0;k<d.length;k++)d[k].src=null,l.removeChild(d[k]);var k=0,p=new Image,
q={},m=60,n=60;p.onload=function(){for(var a=[],d=[],e=[],t=0;t<f/n;t++)for(var v=0;v<b/m;v++){var u=document.createElement("canvas");u.width=m;u.height=n;u.getContext("2d").drawImage(p,v*m,t*n,m,n,0,0,u.width,u.height);a.push(u.toDataURL())}for(k=0;k<a.length;k++)t=document.createElement("img"),t.src=a[k],t.style.zIndex="11",t.className="slicedPic",t.style.top=Math.floor(k/(b/m))*n+"px",t.style.left=k%(b/m)*m+"px",l.appendChild(t),d.push(t),q[a[k]]=k;e=h(a);a.length=0;setTimeout(function(){g.style.zIndex=
"1"},20);c.timer1=setInterval(function(){if(0===e.length)clearInterval(c.timer1);else for(var a=e.shift();0<a.length;)s(d[q[a.shift()]],n,m)},40)};p.src=g.src;setTimeout(function(){a.done="yes"},1500)}
function slicePicShow_diagonal2(l,d,g,e,b,f,c,a,s){function h(a){for(var c=[],d=b/m-1,g=0;g<f/n+b/m-1;g++){var h=[];if(g<b/m){var e=g;for(h.push(a[e]);e+b/m-1<a.length&&Math.floor(e/(b/m))!==Math.floor((e+b/m-1)/(b/m));)e=e+b/m-1,h.push(a[e])}else for(e=d+=b/m,h.push(a[e]);e<a.length&&Math.floor(e/(b/m))!==Math.floor((e+b/m-1)/(b/m));)e=e+b/m-1,h.push(a[e]);c.push(h)}return c}clearInterval(c.timer1);a.done="no";for(var k=0;k<d.length;k++)d[k].style.zIndex="1";g.style.zIndex="12";e.style.zIndex="10";
d=l.getElementsByClassName("slicedPic");for(k=0;k<d.length;k++)d[k].src=null,l.removeChild(d[k]);var k=0,p=new Image,q={},m=60,n=60;p.onload=function(){for(var a=[],d=[],e=[],t=0;t<f/n;t++)for(var v=0;v<b/m;v++){var u=document.createElement("canvas");u.width=m;u.height=n;u.getContext("2d").drawImage(p,v*m,t*n,m,n,0,0,u.width,u.height);a.push(u.toDataURL())}for(k=0;k<a.length;k++)t=document.createElement("img"),t.src=a[k],t.style.zIndex="11",t.className="slicedPic",t.style.top=Math.floor(k/(b/m))*
n+"px",t.style.left=k%(b/m)*m+"px",l.appendChild(t),d.push(t),q[a[k]]=k;e=h(a);a.length=0;setTimeout(function(){g.style.zIndex="1"},20);c.timer1=setInterval(function(){if(0===e.length)clearInterval(c.timer1);else for(var a=e.shift();0<a.length;)s(d[q[a.shift()]],n,m)},40)};p.src=g.src;setTimeout(function(){a.done="yes"},1500)}function fadeOut2(l,d,g){var e=100,b=null,b=setInterval(function(){0===e?clearInterval(b):(e-=2,l.style.opacity=e/100,l.style.filter="alpha(opacity="+e+")")},10)}
function HeightToZero(l,d,g){var e=d,b=100,f=null,f=setInterval(function(){0===e?clearInterval(f):(e-=1,b-=2,l.style.height=e+"px",l.style.width=g+"px",l.style.top=parseInt(l.style.top)+1+"px",l.style.opacity=b/100,l.style.filter="alpha(opacity="+b+")")},10)}
function blowAwayToLeft(l,d,g){var e=d,b=g,f=100,c=null,c=setInterval(function(){0===e?clearInterval(c):(e-=1,b-=1,f-=5,l.style.height=e+"px",l.style.left=parseInt(l.style.left)-(g-b)+"px",l.style.top=parseInt(l.style.top)-(d-e)+"px",l.style.opacity=f/100,l.style.filter="alpha(opacity="+f+")")},30)}
function blowAwayToRight(l,d,g){var e=d,b=g,f=100,c=null,c=setInterval(function(){0===e?clearInterval(c):(e-=1,b-=1,f-=5,l.style.height=e+"px",l.style.left=parseInt(l.style.left)+(g-b)+"px",l.style.top=parseInt(l.style.top)-(d-e)+"px",l.style.opacity=f/100,l.style.filter="alpha(opacity="+f+")")},30)}
function fallDown(l,d,g){var e=d,b=100,f=null,f=setInterval(function(){0===e?clearInterval(f):(e-=1,b-=2,l.style.height=e+"px",l.style.width=g+"px",l.style.top=parseInt(l.style.top)+(d-e)+"px",l.style.opacity=b/100,l.style.filter="alpha(opacity="+b+")")},30)};